src/Entity/Publicacion.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PublicacionRepository")
 * @Vich\Uploadable
 */
class Publicacion
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titulo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Arquitecto;

    /**
     * @ORM\Column(type="text")
     */
    private $Descripcion;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Imagen;

    /**
     * @Vich\UploadableField(mapping="imagenes_obra", fileNameProperty="Imagen")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Imagen", mappedBy="publicacion", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $imagenes;

    public function __construct()
    {
        $this->imagenes = new ArrayCollection();
    }


    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->Titulo;
    }

    public function setTitulo(string $Titulo): self
    {
        $this->Titulo = $Titulo;

        return $this;
    }

    public function getArquitecto(): ?string
    {
        return $this->Arquitecto;
    }

    public function setArquitecto(string $Arquitecto): self
    {
        $this->Arquitecto = $Arquitecto;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->Descripcion;
    }

    public function setDescripcion(string $Descripcion): self
    {
        $this->Descripcion = $Descripcion;

        return $this;
    }

    public function getImagen(): ?string
    {
        return $this->Imagen;
    }

    public function setImagen($Imagen): self
    {
        $this->Imagen = $Imagen;

        return $this;
    }

    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt($updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|Imagen[]
     */
    public function getImagenes(): Collection
    {
        return $this->imagenes;
    }

    public function addImagene(Imagen $imagene): self
    {
        if (!$this->imagenes->contains($imagene)) {
            $this->imagenes[] = $imagene;
            $imagene->setPublicacion($this);
        }

        return $this;
    }

    public function removeImagene(Imagen $imagene): self
    {
        if ($this->imagenes->contains($imagene)) {
            $this->imagenes->removeElement($imagene);
            // set the owning side to null (unless already changed)
            if ($imagene->getPublicacion() === $this) {
                $imagene->setPublicacion(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->Titulo;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/contactos.html.twig
{% extends "index.html.twig" %}

{% block title %}ARQUINEA: Obras{% endblock %}
        
        {% block body %}
        <div class="container container-normal bg-light">
                <hr>
                <div class="d-flex justify-content-center fondo-negro">
                    <h2>
                        Contactos:
                    </h2>
                </div>
                <hr>
                {% for contacto in contactos %}
                    <h3>
                        {{ contacto.titulo }}
                    </h3>
                    <p>
                        {{ contacto.informacion }}
                    </p>
                {% endfor %}
                <hr>
        </div>
        {% endblock %}

{% block javascripts %}
{% endblock %}

templates/documentos.html.twig
{% extends "index.html.twig" %}

{% block title %}ARQUINEA: Obras{% endblock %}
        
        {% block body %}
        <div class="container container-normal bg-light">
                <hr>
                <div class="d-flex justify-content-center fondo-negro">
                    <h2>
                        Documentos:
                    </h2>
                </div>
                <hr>
                {% for documento in documentos %}
                    <h3>
                        {{ documento.titulo }}
                    </h3>
                    <p>
                        {{ documento.descripcion }}
                    </p>
                    <a class="btn btn-light boton-dorado" href="{{asset('documentos/'~documento.archivo)}}">
                        Descargar
                    </a>
                {% endfor %}
                <hr>
        </div>
        {% endblock %}

{% block javascripts %}
{% endblock %}

templates/index.html.twig
<!DOCTYPE html>
<html>
    <head>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-99149413-1"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-99149413-1');
        </script>

        <meta charset="UTF-8">
        <title>{% block title %}ARQUINEA{% endblock %}</title>
        <link rel='icon' type='image/png' href="{{ asset('images/AN.png') }}" />
        {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('webpack/css/sin_node.css') }}">
        {% endblock %}

        <style>
            .pagination>.page-item>.page-link{
                background-color: #232021;
                color:#e1cead;
            }

            .pagination>.disabled>.page-link{
                color:grey;
            }
            .pagination>.active>.page-link{
                background-color: #e1cead;
                color:#232021;
                border-color: #c29c69;
            }

            .pagination>.footable-page>.footable-page-link, .pagination>.footable-page-nav>.footable-page-link{
                background-color: #232021;
                color:#e1cead;
            }

            .footable .pagination > .disabled > a{
                background-color: #232021;
                color:grey;
            }

            .footable .pagination > .active > a, .footable .pagination > .active > span{
                background-color: #e1cead;
                color:#232021;
                border-color: #c29c69;
            }

            .boton-dorado{
                background-color: #e1cead;
            }

            .footable-filtering-search>.input-group>.input-group-btn>.btn-primary{
                background-color: #e1cead !important;
                border-color: #c29c69;
            }
        </style>

    </head>
    <body class="fondo-negro">
        <div class="banner d-flex justify-content-center align-items-center">
            <div class="text-center">
                <h1><big><big>
                    ARQUINEA
                </big></big></h1>
                <h2>
                    Arquitectura en el Nordeste Argentino
                </h2>
            </div>
            
        </div>
        
    	<nav class="navbar navbar-expand-lg navbar-light fondo-navbar">
		  <a class="navbar-brand" href="{{ path('index') }}">ARQUINEA</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">
		      <li class="nav-item active">
		        <a class="nav-link" href="{{ path('index') }}"><i class="fas fa-home"></i> Inicio<span class="sr-only">(current)</span></a>
		      </li>
		      <li class="nav-item active">
		        <a class="nav-link" href="{{ path('obras') }}"><i class="fas fa-hotel"></i> Obras</a>
		      </li>
		      <li class="nav-item active">
		        <a class="nav-link" href="{{ path('documentos') }}"><i class="fas fa-file-signature"></i> Documentos</a>
		      </li>
		      <li class="nav-item active">
		        <a class="nav-link" href="{{ path('contactos') }}"><i class="fas fa-address-book"></i> Contacos</a>
		      </li>
		  </div>
		</nav>
		<div>
		</div>

        {% block body %}
        <div class="container container-normal bg-light">
            <hr>
            <div class="d-flex justify-content-center fondo-negro">
                <h2>
                    Ultimas Obras:
                </h2>
            </div>
            <hr>
            
            {# table body #}
            {% for publicacion in pagination %}
                <tr {% if loop.index is odd %}class="color"{% endif %}>
                    
                    <div class="d-flex justify-content-center">
                        <h2>
                            {{ publicacion.titulo }}
                        </h2>
                    </div>
                    <div class="d-flex justify-content-center">
                            <h2>
                            <img src="{{asset('obras/imagenes/'~publicacion.imagen)}}" class="img-fluid">
                            </h2>
                    </div>
                    <h4>
                        Arquitecto: {{ publicacion.arquitecto }}
                    </h4>
                    <p>
                        {% autoescape false %}
                            {{ publicacion.descripcion|striptags|slice(0, 300) }}...
                        {% endautoescape %}
                    </p>
                    <p>
                        <a class="btn btn-light boton-dorado float-right" href="{{ path('obra', {'id': publicacion.id}) }}">Seguir Leyendo</a>
                    </p>
                    <p>
                            <div class="fb-share-button" data-href="{{ absolute_url(path('obra', {'id': publicacion.id})) }}" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2F{{ path('obra', {'id': publicacion.id}) }}%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Compartir</a></div>
                    </p>
                    <p>
                            <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-url="{{ absolute_url(path('obra', {'id': publicacion.id})) }}" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                    </p>
                    <hr>
                </tr>
            {% endfor %}
            {# display navigation #}
            
            <div class="d-flex justify-content-center">
                {{ knp_pagination_render(pagination) }}
            </div>
        </div>
        {% endblock %}

        {% block footer %}
       	<div class="d-flex justify-content-center text-light fondo-negro">
       		<div>
	       		<div class="d-flex justify-content-center">
	       			<div>Pagina creada por Grupo de Desarrollo <a href="http://www.100monos.com">100monos</a></div>
	       		</div>
	       		<div>Wallpaper-in-black-and-gold <a href='https://www.freepik.com/free-vector/modern-mosaic-wallpaper-in-black-and-gold_3229638.htm'>Designed by Rawpixel.com</a></div>
	       	</div>
       	</div>
        {% endblock %}
        <script src="https://code.jquery.com/jquery-git.js"></script>
        <script src="{{ asset('webpack/bootstrap/js/bootstrap.min.js') }}"></script>
        <script src="{{ asset('webpack/footable/compiled/footable.js') }}"></script>
        <script src="{{ asset('webpack/featherlight/release/featherlight.min.js') }}"></script>
        <script src="{{ asset('webpack/featherlight/release/featherlight.gallery.min.js') }}"></script>
        <script src="{{ asset('webpack/js/sin_node.js') }}"></script>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v3.2';
        fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        {% block javascripts %}
        {% endblock %}
    </body>
</html>

templates/obras.html.twig
{% extends "index.html.twig" %}

{% block title %}ARQUINEA: Obras{% endblock %}
        
        {% block body %}
        <div class="container container-normal bg-light">
            <hr>
            <div class="d-flex justify-content-center fondo-negro">
                <h2>
                    Listado De Obras:
                </h2>
            </div>
            <hr>
                        <!-- Table Markup -->
            <table class="table footable" data-filtering="true" data-sorting="true" data-empty="Sin Obras" data-paging-count-format="{CP} de {TP}"
            data-paging="true" data-paging-size="2" data-filter-placeholder="Buscar">
                <thead>
                    <tr>
                        <th>Titulo</th>
                        <th>Arquitecto</th>
                        <th>Imagen</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for publicacion in publicaciones %}
                        <tr>
                            <td>{{ publicacion.titulo }}</td>
                            <td>{{ publicacion.arquitecto }}</td>
                            <td><img width="100px" src="{{ ('obras/imagenes/'~publicacion.imagen) | imagine_filter('squared_thumbnail') }}" class="img-fluid"></td>
                            <td><a class="btn btn-light boton-dorado w-100" href="{{ path('obra', {'id': publicacion.id}) }}">Ver Publicacion</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endblock %}

        {% block javascripts %}
        {% endblock %}

templates/ver_obra.html.twig
{% extends "index.html.twig" %}

{% block title %}{{ publicacion.titulo }} | ARQUINEA{% endblock %}
        
        {% block body %}
        <div class="container bg-light container-normal">
            <hr>
            <div class="d-flex justify-content-center fondo-negro">
                <div class="text-center">
                    <h2>
                        {{ publicacion.titulo }}
                    </h2>
                    <h3>
                        {{ publicacion.arquitecto }}
                    </h3>
                </div>
            </div>
            <hr>
            <div class="d-flex justify-content-center">
                <img src="{{asset('obras/imagenes/'~publicacion.imagen)}}" class="img-fluid">
            </div>
                
                
                {% autoescape false %}
                        {{ publicacion.descripcion }}
                {% endautoescape %}
                
                
                
                <p>
                        <div class="fb-share-button" data-href="{{ absolute_url(path('obra', {'id': publicacion.id})) }}" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2F{{ path('obra', {'id': publicacion.id}) }}%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Compartir</a></div>
                </p>
                <p>
                        <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-url="{{ absolute_url(path('obra', {'id': publicacion.id})) }}" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                </p>
                <div>
                    
                    <section
                    data-featherlight-gallery
                    data-featherlight-filter="a"
                    >
                    <h4>
                        Galeria de Fotos:
                    </h4>
                        {% for imagen in publicacion.imagenes %}
                            <a href="{{ asset('obras/imagenes/'~imagen.path) }}"><img src="{{ ('obras/imagenes/'~imagen.path) | imagine_filter('squared_thumbnail') }}"></a>
                        {% endfor %}
                    </section>
                </div>
                
                <hr>
        </div>
        {% endblock %}